### ISSUE TITLE
bind sync index to account

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#163]
When the user changes his account (for example by changing the password on another client), synced folders will use the "old" syncIndex but have an empty folder remotely for syncing. Thus, the client will assume that everything has remotely been deleted by intent and will delete everything locally.

By binding the syncIndex to the account (username / prefix / whatever), there would be no syncIndex = empty syncIndex and the client would re-upload everything he finds locally, which is probably more intuitive for the user and definitely less risky for local files.

**Comment by julianseeger** [comment]
depends on Qabel/qabel-core#491

**Comment by jmt85** [comment]
see Qabel/qabel-block #44

**Comment by jmt85** [comment]
ftr: username is ok

**Comment by julianseeger** [comment]
btw.: don't think Qabel/qabel-block#44 is related at all

**Comment by jmt85** [comment]
I think so, too. It was linked before the issue moved to qabel-block. I delete the reference.
