### ISSUE TITLE
missing stuff

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#167]
- [x] **(wontfix)** Programme und Funktionen: qabel icon fehlt
- [ ] Identity bearbeiten: E-Mail und Telefonnummer [Android compatibility]
- [x] Bei Unternavi (icons unten) sollten die Naviitems (Hauptnavi) deselected werden
- [x] translate share message
- [x] translate sync setup messages
- [x] Hockeyapp does not receicve all information (mail / name)
- [x] installer: ask for config deletion
- [ ] ~~quota~~

Sonstiges:
- [x] Logo aus Background entfernen
- [x] tooltip bei navi iconsqabel.github.io
- [ ] delete contacts
- [ ] delete syncs

Bug:
- [x] freeze bei hockeyapp feedback abschicken (wenn Name und Email und Text ausgefüllt sind unter Gnome3)
- [x] remotefs view bei Windows kaputt

**Comment by jmt85** [comment]
create new ticket for the open points
