### ISSUE TITLE
dark font on dark background

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#198]
In Windows the tool tipps have dark font on dark background

https://rink.hockeyapp.net/manage/apps/289338/feedback/445706

**Comment by julianseeger** [comment]
unable to reproduce:
![tooltip](https://cloud.githubusercontent.com/assets/3258762/13500761/3330330a-e164-11e5-86f3-806d7fca2c9b.PNG)

**Comment by jasinai** [comment]
I think I could reproduce this:
click on a file and then hover over the icons

**Comment by jmt85** [comment]
i see black font ...

win 8.1 pro 64 bit

**Comment by julianseeger** [comment]
thanks @jasinai 
![tooltip_fail](https://cloud.githubusercontent.com/assets/3258762/13501145/d1f240c2-e165-11e5-95e4-58946e1301d1.PNG)
