### ISSUE TITLE
notification for incoming new messages  

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#199]
In the Desktop Application a notification should be show in the left Navigation and the corresponding contact in the contact list when a new messages arrived

see https://rink.hockeyapp.net/manage/apps/289338/feedback/446272#

- [x] indicator in contact list
- [x] indicator in navi
- [ ] load unread messages on startup

**Comment by mr-gosh** [comment]
![log-conversation](https://cloud.githubusercontent.com/assets/3028703/13666526/3bdc70d8-e6b2-11e5-9d95-bd122fb07f8e.png)

**Comment by julianseeger** [comment]
@mr-gosh what about that:
![anthracite-indicators](https://cloud.githubusercontent.com/assets/3258762/14603102/27786f88-056c-11e6-86ca-719fcfe107d1.png)

**Comment by julianseeger** [comment]
or that ;)
![inverted](https://cloud.githubusercontent.com/assets/3258762/14603150/66f3bd5c-056c-11e6-9223-1de171e0e2c1.png)

**Comment by mr-gosh** [comment]
I like the second approach a lot more...

**Comment by mr-gosh** [comment]
Btw. I recognized thst the android notifications have a automatic scaling in there "unread count" so a longer number creates not a circle anymore but a rounded box... - just as a suggestion... ;-)
