### ISSUE TITLE
Qabel Line at Login Screen

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#214]
The Line at the Login Screen should be the "Qabel Line"

Line comes later

**Comment by jmt85** [comment]
***Einmal Grau:

.hr-fade-from-grey {
    border: 0;
        border-top-width: 0px;
        border-right-width: 0px;
        border-bottom-width: 0px;
        border-left-width: 0px;
        border-top-style: none;
        border-right-style: none;
        border-bottom-style: none;
        border-left-style: none;
        border-top-color: -moz-use-text-color;
        border-right-color: -moz-use-text-color;
        border-bottom-color: -moz-use-text-color;
        border-left-color: -moz-use-text-color;
        -moz-border-top-colors: none;
        -moz-border-right-colors: none;
        -moz-border-bottom-colors: none;
        -moz-border-left-colors: none;
        border-image-source: none;
        border-image-slice: 100% 100% 100% 100%;
        border-image-width: 1 1 1 1;
        border-image-outset: 0 0 0 0;
        border-image-repeat: stretch stretch;
    height: 1px;
    background: linear-gradient(to right, rgba(0,0,0, 0.0) 0%,
rgba(51,51,51, 1.0) 10%, rgba(51,51,51, 1.0) 90%, rgba(0,0,0, 0.0) 100% );
        background-color: transparent;
        background-image: linear-gradient(to right, transparent 0%,
rgb(51, 51, 51) 10%, rgb(51, 51, 51) 90%, transparent 100%);
        background-repeat: repeat;
        background-attachment: scroll;
        background-position: 0% 0%;
        background-clip: border-box;
        background-origin: padding-box;
        background-size: auto auto;
}





***Einmal Weiß:

.hr-fade-from-white {
    border: 0;
        border-top-width: 0px;
        border-right-width: 0px;
        border-bottom-width: 0px;
        border-left-width: 0px;
        border-top-style: none;
        border-right-style: none;
        border-bottom-style: none;
        border-left-style: none;
        border-top-color: -moz-use-text-color;
        border-right-color: -moz-use-text-color;
        border-bottom-color: -moz-use-text-color;
        border-left-color: -moz-use-text-color;
        -moz-border-top-colors: none;
        -moz-border-right-colors: none;
        -moz-border-bottom-colors: none;
        -moz-border-left-colors: none;
        border-image-source: none;
        border-image-slice: 100% 100% 100% 100%;
        border-image-width: 1 1 1 1;
        border-image-outset: 0 0 0 0;
        border-image-repeat: stretch stretch;
    height: 1px;
    background: linear-gradient(to right, rgba(0,0,0, 0.0) 0%,
rgba(255,255,255, 1.0) 10%, rgba(255,255,255, 1.0) 90%, rgba(0,0,0, 0.0)
100% );
        background-color: transparent;
        background-image: linear-gradient(to right, transparent 0%,
rgb(255, 255, 255) 10%, rgb(255, 255, 255) 90%, transparent 100%);
        background-repeat: repeat;
        background-attachment: scroll;
        background-position: 0% 0%;
        background-clip: border-box;
        background-origin: padding-box;
        background-size: auto auto;
}

**Comment by julianseeger** [comment]
- [x]
