### ISSUE TITLE
reorder buttons at accounting screen

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#215]
The Buttons get to the top and get a new sequence.

Sequence is to define later.

**Comment by jmt85** [comment]
new mockups available

**Comment by mr-gosh** [comment]
![identity](https://cloud.githubusercontent.com/assets/3028703/15398780/59a0f53e-1de5-11e6-885a-71e5d02a7207.png)

**Comment by julianseeger** [comment]
For obvious reasons I would prefer to rename
`export identity as .qid` to `export private Key as .qid` (or "to file" instead of "to file"?)
and to add
`export public Key as .qco`

**Comment by audax** [comment]
ack, although we should maybe change the wording again after some user feedback.
