### ISSUE TITLE
Layout Bug at Quota at Windows

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#219]
Quota at Windows is shifted down.

**Comment by julianseeger** [comment]
![quota](https://cloud.githubusercontent.com/assets/3258762/13606141/23c8c40a-e54b-11e5-8a47-525cca40ea7a.PNG)

doesn't look shifted anymore (the inner bar was too far up), even though it doesn't look rectangular like the mockups yet.

**Comment by jmt85** [comment]
a final test on win10 to verify
