### ISSUE TITLE
ensure single instances of entites

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#225]
The drop message repository persists drop messages including the full identity and contact objects. This way, after unserializing them, multiple instances of the same identity and contact are used in the application which sould not be. Storing the keyId combined with the information which one is the identity and which one is the contact should be enough identify both using the according Repositories.

**even though markes as bug, this is more an architectural issue or potential bug**

**Comment by julianseeger** [comment]
*maybe* this can be combined with the Repo rewrite that removes the `Persistence` that needs to be done

**Comment by jmt85** [comment]
is it combined?

**Comment by julianseeger** [comment]
maybe

**Comment by jmt85** [comment]
ok, then check it ;)

**Comment by audax** [comment]
This is resolved with the usage of the entity manager
