### ISSUE TITLE
EV Code Signing Certificate

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-desktop#231]
We need a EV Code Signing Certificate to get around MS SmartScreen.

https://blogs.msdn.microsoft.com/ie/2012/08/14/microsoft-smartscreen-extended-validation-ev-code-signing-certificates/

**Comment by julianseeger** [comment]
0.10.0 is signed ... please check anyone that smartscreen behaves better now...

**Comment by thechauffeur** [comment]
It works with the released setup.exe
