### ISSUE TITLE
QR export of contact

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#256]

**Comment by audax** [comment]
We could also just set it to the highest setting (short dropurl) and remove the feature from android. I don't think it has any benefit to have it user controllable.

**Comment by julianseeger** [comment]
don't know where it should be placed ... or should it be a popup ... or just shown in the (currently not used there) details pane for an identity?

**Comment by mr-gosh** [comment]
most simple would be - if someone clicks on the avatar of his id in the upper left corner something like the below appears

![qr-overlay](https://cloud.githubusercontent.com/assets/3028703/13749218/a8a03136-ea00-11e5-84de-83d675c3f979.png)

**Comment by mr-gosh** [comment]
ok - we argued a bit - and we want the avatar to show up with this Overlay QR-Code and that the menue shows the same qr-code overlay in the "share Public Key by QR" menue entry.

![identity-show-qr](https://cloud.githubusercontent.com/assets/3028703/13851560/f9893420-ec5e-11e5-94b5-e060be21972d.png)
