### ISSUE TITLE
Some licenses are missing in desktoop about screen

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-desktop#280]
the following licenses are missing in the desktop about screen:

Material Design Icons:
> Google Material Design Icons - Attribution 4.0 International
> https://github.com/google/material-design-icons/blob/master/LICENSE

Material Design Icons - based Icons:
> Community Icons - SIL Open Font License 1.1
> http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web

if you use the roboto font in the desktop:

License for 'Roboto' Font:
> Apache License - Font data copyright Google 2012
> Apache License
> Version 2.0, January 2004
> http://www.apache.org/licenses/

as mentioned in:
https://github.com/Qabel/qabel-android/issues/189

**Comment by julianseeger** [comment]
[Source Sans Pro](https://www.google.com/fonts/specimen/Source+Sans+Pro), roboto has been removed from the desktop client

@jmt85 is it confirmed that this issue is in the sprint backlog => not included in beta.1

**Comment by julianseeger** [comment]
![icon-licenses](https://cloud.githubusercontent.com/assets/3258762/13778969/fd29dd7a-eab8-11e5-89b3-c66762ac23b0.png)

Looks like that now. After the first beta maybe we can group them together with the jar dependencies that are grouped by license.
