### ISSUE TITLE
add Qabel thanks 

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#281]
add Qabel thanks to "über/about" like the android app

Alexander Hartmann
Andreas Kassner
Barabara Steuer
Benjamin Schütze
Britta Görtz
Christian Burkert
Daniel Kaminski
Danny Werner
Dennis Weber
Dieta Heilmann
Dustin Fürst
Elisa-Marie Rustemeyer
Elmar Lay
Erik Nikolov
Fabian Träger
Frank Geise
Frank Roebers
Hanno Meetz
Haris Adamopoulou
Jan Schreiber
Jan Wischweh
Jens Kadenbach
Jens Kassert
Joachim Girschik
Julian Seeger
Lennart Henke
Malte Zobel
Marcus Amler
Markus Thimm
Martha Lisiewitz
Martin Bostelmann
Martin Linke
Matthaeus Kozlowski
Michael Koch
Mike Hahm
Mirco Pietsch
Moritz Kaynert
Moritz Schmidt
Nicola Hauke
Norbert Najderek
Oliver Weidner
Patrick Engelking
Paul Rösler
Peter Leppelt
Philipp Schröder
Reinhard Sczesny
Rickuz
Sascha Nanninga
Sven Busche
Sven Klose
Tarkan Firat
Thomas Schuster
Valerie Whyte
Wulf Bolte

**Comment by jmt85** [comment]
see #357

**Comment by julianseeger** [comment]
ftr: imho a plain list of names under a list of dependencies will look really bad...

**Comment by mr-gosh** [comment]
Perhaps a button with a thanks pop-up?

**Comment by julianseeger** [comment]
fullscreen black background with sliding credits would be nice ;)
I'm going to prototype it and add a screenshot

**Comment by mr-gosh** [comment]
Pop-up-thanks:
![about-thanks](https://cloud.githubusercontent.com/assets/3028703/15394084/fe4aa202-1dd0-11e6-8e0e-7e9da62d9792.png)
