### ISSUE TITLE
tray icon is not removed on close

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#293]
When closing the application, the tray icon is not removed. The behavior might be system dependent but on windows it is removed on hover. There should be some shutdown hook (or similar) to remove the icon when the application is closed.

**Comment by jmt85** [comment]
it is finish, right?

**Comment by julianseeger** [comment]
nope, Fixed with `0.6.0` but re-introduced with `0.6.1` because it seems to crash the javafx stage somehow...
