### ISSUE TITLE
(Probably) can't register via Qabel Desktop

### ISSUE THREAD

**Issue by aBothe** [Qabel/qabel-desktop#294]
Hi everyone,

just downloaded Qabel Desktop and tried registering myself on Qabel.
After pressing 'Register', the 'erstellen'-Button just turns red without providing any hint what went wrong or what I did wrongly.
I'll try to use the [web](https://qabel.de/de/registrierung) registration for now -- maybe it'll be just satisfying to do it over there.

**Comment by julianseeger** [comment]
there should be a tooltip on the red button providing more information

**Comment by aBothe** [comment]
My thought as well, but it remained empty.
In the mean time I managed to register on the Qabel web page.
This worked flawlessly, but nevertheless I can't sign up in the Qabel desktop client now.
The client just doesn't give any feedback.

Are there any logs I may provide to you?

**Comment by julianseeger** [comment]
unfortunately no, currently. The logs are not written correctly on the distributed version but we're working on it.

**Comment by audax** [comment]
The logs are now written in the (next) release version and then we can open a new issue if this problem persists.
