### ISSUE TITLE
endless loop due sync

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#298]
Trace from Feedback

"- Ordner angelegt
- Sync angelegt
- Dateien wurden hochgeladen
- Ordner mit Dateien gelöscht, Unterordner angelegt
- Zweiten Sync angelegt, diesmal mit dem Unterordner im Zielpfad
- Aber jetzt kommt die Katastrophe: Im Browser wird statt der Dateiübertragungen
unendlich oft der Unterordner neu angelegt!
Ich kann das nicht mehr stoppen. Auch das Löschen des höchsten Ordners hilft nur bis zum nächstenStart des Clients." 

https://rink.hockeyapp.net/manage/apps/289338/feedback/462997

**Comment by julianseeger** [comment]
Given I have locally a folder "syncme" with a subfolder "syncme" (lets call them A and B)...
and remotely I have a folder "syncme" (lets call it C)

When I create two syncs (X and Y)
and X targets the parent "syncme" (A) locally and "syncme" (C) remotely
and Y targets the child "syncme" (B) locally and "syncme" (C) remotely too

Then X will find the child "syncme" (B) in its local sync root (A) it will upload it to /syncme/syncme (alias C/B)
Then Y will recognize the newly created folder "syncme" in its remote sync root /syncme (C) and download it ... to create B/syncme locally or syncme/syncme/syncme
Then X will find the newly created local syncme/syncme/syncme (relative `/syncme/syncme`) and upload it to /syncme/syncme/syncme (or C/syncme/syncme) ... which Y will recognize and download ... etc pp

Actually this behavior is absolutely correct.
Other question is ... how to prevent it:
A) allow deletion of syncs (#182)
B) allow modification of sync dirs (#299)
C) don't allow two syncs in subdirectories (no ticket, but wouldn't had helped the user)

**Comment by jmt85** [comment]
sww #299

**Comment by julianseeger** [comment]
Then I take this issue as **C)** C) don't allow two syncs in subdirectories
