### ISSUE TITLE
Folder Sync stopped

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#304]
Folder Sync is stopped totally if upload fails for one file.

The folder sync must skip the failed file and upload the rest as usual

**Comment by julianseeger** [comment]
I think the upload actually never fails but gets stucked and never times out, thus blocking all other transfers

**Comment by julianseeger** [comment]
There are a lot of issues that lead to a sync- (or general transfer-) stop. I try to name and fix the most probable ones:

- [ ] **http connections are not closed** on download => leading an empty connection pool (=lock)
- [ ] the TransferManager doesn't catch all **exceptions** and thus the thread may terminate (most of them are ConcurrentModificationExceptions)
- [ ] the UI is updated on every stream read action for up- and downloads (every couple of bytes) leading to **UI freezes** and may **lock** code that slows down the transfers (neither the updates nor locks locking the transfers are ok)

**Comment by julianseeger** [comment]
lol I mentioned every ticket except the original XD
