### ISSUE TITLE
Feedback comment

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#307]
Comment / popup if a feedback send correctly

example

"Thank you for your feedback"

**Comment by nnice** [comment]
@jmt85 @julianseeger 

how is that?

![bildschirmfoto vom 2016-07-19 13-43-35](https://cloud.githubusercontent.com/assets/16781049/16948776/e1e277d2-4db6-11e6-815e-eb7cd6c249ad.png)
