### ISSUE TITLE
show identity for sync

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#308]
Overview which sync belongs to which identity

https://rink.hockeyapp.net/manage/apps/289338/feedback/471608#

**Comment by mr-gosh** [comment]
in the sync overview the corresponding identity is displayed though its avatar:
![sync-overview](https://cloud.githubusercontent.com/assets/3028703/15217611/a31b54c2-185c-11e6-9b06-a6d43b6518a2.png)

during creation of new sync folders, the corresponding identity can be selected trough a drop down:
![sync-add](https://cloud.githubusercontent.com/assets/3028703/15217639/bfd20c32-185c-11e6-99d1-65fb2227f17c.png)
