### ISSUE TITLE
Start minimized

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#326]
...if possible (if a valid account and identity exist)

**Comment by jmt85** [comment]
Result of the discussion:
start minimized, if a login token is available
ask during the installation whether qabel starts automatically at windows start

**Comment by julianseeger** [comment]
Even though https://github.com/Qabel/qabel-desktop/pull/402 makes this start "iconified", the term "minified" was misleading here, wasn't it?
As far as I understood it, the requested behavior is that the client is not visible, but the tray icon is. And via the trac icon you can open/show the main window. So "not visible" like if you click the close button.

The current behavior is: it is iconified = minimized to the task bar ... not minimized to tray.
And the show entry on the tray icon does not open the main window. It does nothing in that case.

Imho closing the window was the requested behavior, not what https://github.com/Qabel/qabel-desktop/pull/402 did. @thechauffeur @jmt85

**Comment by audax** [comment]
Ouch, I shouldn't have merged the PR, I somehow thought that was already cleared up…

**Comment by julianseeger** [comment]
The 
> ask during the installation

part is missing, too. Even though I don't know how to do that and it wasn't included in the estimation.

**Comment by enkore** [comment]
Shouldn't

>  ask during the installation whether qabel starts automatically at windows start

be a separate ticket? Feels rather unrelated to starting minimized to me.

**Comment by julianseeger** [comment]
@jmt85 schedule this to todays meeting?

**Comment by jmt85** [comment]
k

**Comment by julianseeger** [comment]
Need to reopen this.
Login Failures are not handled. If the client can't login, the LoginWindow get's hidden as if the login was successful. There is no point in hiding the window in that case.
