### ISSUE TITLE
reduce conflict window for uploads

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#331]
get due dm upload → 54 kb
data loss can occur
Bulk upload has no influence

Solutions
etags for upload → reduce reduces the conflict window strong

**Comment by julianseeger** [comment]
note: the etag of the old dm/block that gets overridden is transferred

**Comment by julianseeger** [comment]
depends on Qabel/qabel-core#491

**Comment by jmt85** [comment]
Qabel/qabel-core#491 was move to qabel drop
now depends on Qabel/qabel-block#44

**Comment by audax** [comment]
Can this be implemented directly in the Core? @julianseeger 
This only concerns DMs and we don't need to cache the ETag because we download the DM before we updated it anyway.

**Comment by julianseeger** [comment]
Yep, I hope so, too.
