### ISSUE TITLE
upload the contact [information] of an identity to the index server

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#335]
It should be possible to upload contact to the register server.

for new created identities
for already existing

**Comment by julianseeger** [comment]
To be more clear: you mean "upload the contact [information] of an identity"?
The title sounds more like "upload my contact list to the register server" ... that shouldn't happen imho

**Comment by jmt85** [comment]
> To be more clear: you mean "upload the contact [information] of an identity"? 

yes, i change the title
