### ISSUE TITLE
add unknown contact by received message

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#338]
If someone receives a message from an unknown contact, the user should have the possiblity to add this contact to his contacts and assign it to his identity.

**Comment by mr-gosh** [comment]
![contacts-unassigned](https://cloud.githubusercontent.com/assets/3028703/15742628/74e75ab4-28c0-11e6-8550-5d737d749516.png)

**Comment by mr-gosh** [comment]
Keep in mind, that the "Windows Toast Messages" should be interactive - and the user should be redirected to the above window with the pop-up when clicking the toast message of the "new contact added" toast - so the user can assign it to an identity immediately...

**Comment by audax** [comment]
Afaik we can't have interactive windows notifications with JavaFX @mr-gosh

**Comment by audax** [comment]
In addition to assigning contacts:

* Unknown (=new via hello protocol) contacts are shown in the normal contact list, but with a grey avatar
* When opening a chat with an unknown contact, two buttons appear at the top of the chat. An "Accept" button and an "Ignore" button.
* In the contact list, the chooser from the mock image has the following entries:
** "All contacts" that show all unknown and normal for the selected identity
** "New contacts" to show all new contacts for the selected identity
** "Ignored contacts" to show all ignored contacts that contacted the selected identity

Approved by @mr-gosh
