### ISSUE TITLE
upload problem in remote FS browser 

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#348]
If I create a folder in the remote fs browser, it doesn't get synced to android. Also it is not shown in remote folder choice in the sync option dialog.

![fs_bug1](https://cloud.githubusercontent.com/assets/4853105/14781690/4b7cda90-0ae4-11e6-9970-71aa71e42c82.png)

![fs_bug2](https://cloud.githubusercontent.com/assets/4853105/14781693/4cc54fe0-0ae4-11e6-92ca-dd35be3955d2.png)

**Comment by julianseeger** [comment]
I guess that the folder/dm/something is never actually uploaded. That would make the RemoteFolderChooser and android consistent (which is also the state of the remote browser after restarting the client) and the remote fs browser of the current session is buggy.

PS: Estimation based on removing the treesearch before solving this issue

**Comment by julianseeger** [comment]
fixed without touching the treesearch. it was "just" the delayed/bulk autocommit that was broken
