### ISSUE TITLE
using about screen without identity freezes/breaks ui

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#356]
steps to reproduce: 1. qabel-desktop starten 2. keine identität haben 3. auf "about" klicken 4. menü ist kaputt. passiert nicht, wenn es eine identität gibt (linux)

**Comment by nnice** [comment]
@jmt85 @thechauffeur; cant reproduce it. seems to be fixed already

**Comment by jmt85** [comment]
is still broken

**Comment by nnice** [comment]
fixed with referenced PR
