### ISSUE TITLE
show legal text in the client

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#362]
The legal texts must not be only present as a link. Therefore, the full text must be displayed as a text, pop-up or the like.

**Comment by mr-gosh** [comment]
new design of "about screen"
![about](https://cloud.githubusercontent.com/assets/3028703/15392861/1ccdbf40-1dca-11e6-9cbb-8e40ecd48339.png)

**Comment by mr-gosh** [comment]
![about-license](https://cloud.githubusercontent.com/assets/3028703/15394323/96cd328c-1dd2-11e6-9113-4f04ffe9ca7c.png)

**Comment by julianseeger** [comment]
Some padding on the popup and more vertical margin between the "show license" boxes please ;)

**Comment by mr-gosh** [comment]
Well ok - do it that way... ;-)
