### ISSUE TITLE
Identity Creation Needs a Wizard

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-desktop#364]
To guide a user through the identity creation we need a wizard like in android:
Public Name of Identity:
![id-creation-wizard-1](https://cloud.githubusercontent.com/assets/3028703/15397997/56305118-1de2-11e6-8dc9-9256f63ab202.png)

Personal non-public Discription of Communication Group:
![id-creation-wizard-2](https://cloud.githubusercontent.com/assets/3028703/15398004/5aa16eee-1de2-11e6-8784-4eaaaaab9de0.png)

Paranoia Level Indicator:
![id-creation-wizard-3](https://cloud.githubusercontent.com/assets/3028703/15398016/60dfa5fa-1de2-11e6-8747-ff9226d5254c.png)

First Steps Finalized:
![id-creation-wizard-4](https://cloud.githubusercontent.com/assets/3028703/15398028/686ab4d6-1de2-11e6-9fd6-880107e442e3.png)

Optional Register Server Mail Registration:
![id-creation-wizard-5](https://cloud.githubusercontent.com/assets/3028703/15397986/4eef7f00-1de2-11e6-8a94-4acf4d94ac34.png)

Optional Register Server Phone Registration:
![id-creation-wizard-6](https://cloud.githubusercontent.com/assets/3028703/15397972/46d25df6-1de2-11e6-8e8a-ebe32fc01578.png)

Last Step:
![id-creation-wizard-7](https://cloud.githubusercontent.com/assets/3028703/15397959/4221021c-1de2-11e6-8a8b-6c680e4d02ef.png)

**Comment by julianseeger** [comment]
@mr-gosh would you mind adding some dot's to indicate the wizards progress

**Comment by mr-gosh** [comment]
integrated the progress indicator

**Comment by jmt85** [comment]
please do not implement part/image 2 and 3

**Comment by jmt85** [comment]
registerserver = indexserver
