### ISSUE TITLE
Final implementation of Orange Theme

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-desktop#381]
![theme-orange](https://cloud.githubusercontent.com/assets/3028703/15929502/a848775c-2e4d-11e6-9b58-6bdbaec4d961.png)

Please check these facts for proper implementation:
**Left Sidebar:**
* "Normal" State = white (icons and text)
* "mouse-over" state = 80% black (icons and text)
* "active" state = 80% black (icons and text) and white background with drop-shadow at upper and lower edge
* the same for the icons on the lower end of the left sidebar without the drop-shadow

**The Middle-Menue-entry-highlight:**
* "Normal" State = 80% black (icons and text) & no background
* "mouse-over" state = 80% black (icons and text) & 10% black background
* "active" state = 80% black (icons and text) and 30% black background and white sidebar pointer with drop-shadow

**The Buttons:**
* "Normal" State = 80% black (icons, text and outline) & no background
* "mouse-over" state = 50% black (icons, text and outline) & no background
* "active" state = qabel orange (R: 255 G:  89 B:   8) (icons, text and outline) & no background

**Comment by julianseeger** [comment]
@mr-gosh that's what it currently looks like with #405 

**list-items:**
![image](https://cloud.githubusercontent.com/assets/3258762/17402949/eed096f8-5a55-11e6-8254-b8dd0964f52e.png)

**navigation:**
![image](https://cloud.githubusercontent.com/assets/3258762/17403005/326fdcf2-5a56-11e6-8f1d-b59e299ec6c1.png)

**the icons below the navigation:**
![image](https://cloud.githubusercontent.com/assets/3258762/17403029/48c68532-5a56-11e6-9893-00a2cbecd915.png)

**buttons (onmousedown, they are grey on hover):**
![image](https://cloud.githubusercontent.com/assets/3258762/17403068/675a5dde-5a56-11e6-81be-15f75e376280.png)

**PS: the cursor is a hand... the screenshot-tool just changes the cursor**

**Comment by mr-gosh** [comment]
![theme-orange](https://cloud.githubusercontent.com/assets/3028703/17588711/ff404c10-5fd0-11e6-9660-65b35beb2916.png)
![probleme1](https://cloud.githubusercontent.com/assets/3028703/17588910/03af74a0-5fd2-11e6-989d-accfca26939c.png)

**Comment by taynaps** [comment]
add used space bar and calculate used space will be implemented in the ticket #220
