### ISSUE TITLE
Add Sub-Menu to Contact

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-desktop#387]
Here the Mocked Contacts-Menu:
![contacts-menu](https://cloud.githubusercontent.com/assets/3028703/16304021/e847bd0c-3953-11e6-994e-3b99d0bc94ee.png)

**Comment by jmt85** [comment]
Good idea. We will re-design the menu.

Of course not all functions shown above are already implemented. When implementing a feature or function mentioned in the mockup it will be shown as in the mockup.
