### ISSUE TITLE
Core Functions - searching by Name in the remoteFS

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#39]
Extension in the main remoteFS browser UI. 
Searching by name for files and directories.

**Comment by audax** [comment]
See https://github.com/Qabel/qabel-android/blob/master/qabelbox/src/main/java/de/qabel/qabelbox/storage/StorageSearch.java

**Comment by julianseeger** [comment]
Marked as done by @thechauffeur.
