### ISSUE TITLE
RemoteFSBrowser broken

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#400]
Seems to be caused by a jdk update >8u73. Probably [8u91](http://www.oracle.com/technetwork/java/javaseproducts/documentation/8u92-revision-builds-relnotes-2994940.html) If you collapse a folder, the contents stay visible including it's icon (but not the text).

![fs](https://cloud.githubusercontent.com/assets/3258762/17100125/e208352a-526c-11e6-9dee-1008315327f1.png)

**Comment by jmt85** [comment]
We should spike this to know how bad it is and if oracle broke things and not we.

**Comment by audax** [comment]
Fixed in #449
