### ISSUE TITLE
Data loss on qabel update

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#426]
An update from an old qabel version ( @audax please insert the exact version here ) to the current master seems to loose all data. (Maybe it uses another prefix or something like that).

**Comment by audax** [comment]
This is fixed in the core: https://github.com/Qabel/qabel-core/pull/579

**Comment by julianseeger** [comment]
True. Needs to be confirmed / re-tested once it's merged to the core.

**Comment by audax** [comment]
Confirmed with a test release
