### ISSUE TITLE
Syncing - offline/local conflict handling

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#45]
A mechanism to handle local / offline conflicts

**Comment by julianseeger** [comment]
in order to solve this cleanly, the extraction of all merge-logic into two clean 3-way-merge-strategies (up- and download) is probably neccessary

**Comment by julianseeger** [comment]
and the 2s wait for file changes could probably be replaced by [exclusive read locking](http://stackoverflow.com/questions/128038/how-can-i-lock-a-file-using-java-if-possible)

**Comment by audax** [comment]
Could we implement some safeguards for now? @julianseeger 

For example a general rule: Don't ever do stuff outside of the sync folder.

**Comment by julianseeger** [comment]
maybe we can brainstorm some simple rules monday.
