### ISSUE TITLE
Desktop clients send a lot of login requests

### ISSUE THREAD

**Issue by enkore** [Qabel/qabel-desktop#474]
Up to multiple times per minute per client. q-android doesn't exhibit this behaviour.

**Comment by thechauffeur** [comment]
IIRC this is a long standing behavior and we should definitely address it this time after the release.

**Comment by thechauffeur** [comment]
Does this issue mean using the auth token instead of acc+pw?

**Comment by enkore** [comment]
Since the token doesn't expire it should just be stored and used for further requests. Currently it seems that the client logs in again with the user password (/api/v0/auth/login/) for every request sent to the block server.

**Comment by enkore** [comment]
> Does this issue mean using the auth token instead of acc+pw?

See #540
