### ISSUE TITLE
Change private-toggle in Identity Edit

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-desktop#482]
The private-toggle label should not change depending on the state of the toggle. The label should always be "private". The description text should also not change.

The new description text will be posted in this ticket. @thechauffeur

**Comment by thechauffeur** [comment]
german
> Markieren Sie eine Identität als privat, um zu verhindern, dass
Informationen über Ihre Identität auf dem Qabel Index veröffentlicht
werden. Qabel Index ist das öffentliche Kontaktverzeichnis für
Qabeluser. Hinweis: Andere Qabeluser können Ihre Kontaktdaten nicht über
Ihre Telefonnummer oder Ihre E-Mail-Adresse finden, wenn Sie Ihre
Identität als privat markieren.
>
> Zur Bestätigung Ihrer E-Mail-Adresse/Telefonnummer senden wir Ihnen eine
E-Mail/SMS an die genannte Adresse/Nummer.

english
> Tag an identity as private to prevent that any information about your
identity is published on the Qabel Index. Qabel Index is the public
contact directory for Qabel users. Note: If you tag your identity as
private, other Qabel users cannot find your contact details via your
phone number or your e-mail address.
>
> To confirm your e-mail address/telephone number, we will send you an
e-mail/text message to the respective address/number.

**Comment by julianseeger** [comment]
![image](https://cloud.githubusercontent.com/assets/3258762/18876234/231ec978-84c9-11e6-83d7-167ec6e5b881.png)
