### ISSUE TITLE
data lost due editing sync

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#484]
create local folder foo1Local
create local folder foo2Local
create remote folder fooRemote
create sync between foo1Local and fooRemote
add file to foo1Local
change sync from foo1Local to foo2Local
foo2Local empty

expected behavior: foo1Local = foo2Local = fooRemote

edit: after restart Qabel foo2Local is synced
edeit2: behaviour is time-dependent, it can also been all deleted

**Comment by thechauffeur** [comment]
For now, deactivate this function.

**Comment by thechauffeur** [comment]
Because it has somehow slipped through. This function is not really needed anyway and might even confuse users (even if working properly). We don't need an edit sync feature.

**Comment by thechauffeur** [comment]
This issue should be closed but by which PR?

**Comment by audax** [comment]
Closed by https://github.com/Qabel/qabel-desktop/pull/485 which disabled the edit function.
