### ISSUE TITLE
Contacts that are identities vanish

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#487]
Two identities on one desktop client: Alice & Bob

1 Upload Alice to the index server
2 select bob
3 search alice on the index server (as bob)
4 assign alice (contact) to bob (identity)
5 select alice as the active identity
6 select bob as the active identitiy
=> alice is no longer in bobs contact list (even though it was after step 4)

Don't know what happens if the imported contact is not an identity, too

**Comment by audax** [comment]
Should be fixed in the core in 0.25.3, there was a similar bug in the android client:
https://github.com/Qabel/qabel-android/issues/681

**Comment by julianseeger** [comment]
still exists with 0.25.3
