### ISSUE TITLE
index search with email containing digits

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#493]
...fails because the phonenumber formatter gets activated and reformats them to a number...

**Comment by enkore** [comment]
is_email = '@' in input

**Comment by julianseeger** [comment]
normally, this happens before typing the @
username12345@bla.com ... as soon as you type the "12", it get's reformatted ... it's a feature, not a bug ;)

**Comment by enkore** [comment]
Hmm, you can't really determine from any prefix whether it's an email or phone number until you get an @ or are "finished". Some ISPs even issued emails where the mailbox actually *is* a valid phone number...

**Comment by audax** [comment]
We probably shouldn't reformat it after we have a successful hit. Maybe not even then

**Comment by julianseeger** [comment]
Are the requests normalized Server side? Like if I type a phone number without language code, what happens? Otherwise we need two Inputs

**Comment by mr-gosh** [comment]
I was surprised that filling in a phone number without country code works at all - perhaps we do it like in my mockups...

**Comment by julianseeger** [comment]
The Idea was to Autoformat the users phone number using his locale but that is error prone and thus we need to show the result to the user so that he can fix it on failure... but that only works if we know that it actually is a phone number and not an Email address

**Comment by julianseeger** [comment]
What about this:
![image](https://cloud.githubusercontent.com/assets/3258762/18907054/537c7682-856a-11e6-845d-d19e9d90625d.png)
The user can type whatever he wants but we show, what exactly we are searching for.
This way, the user can adjust the input if it's not what he wanted (like adding a language prefix if neccessary) and can reach the "@" symbol without being interrupted.

**Comment by audax** [comment]
This looks way too reasonable, we need to find a more complicated solution.

**Comment by thechauffeur** [comment]
I always asked myself why some other interfaces use a drop down menu for selecting the country and actually working with (mobile) phone numbers -- and seeing the problems -- make me understand this :) Now I like the idea of the mockups but without further discussions about this (after the release) I'm still not sure about this. So we should stick with the solution we already have.

**Comment by julianseeger** [comment]
>So we should stick with the solution we already have.

Then you are not able to search vor emails containing digits in front of the @
