### ISSUE TITLE
Update imprint

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-desktop#496]
All occurrences of our imprint inside the client / installer etc. must be updated to much the imprint at our website.

german
https://qabel.de/de/impressum

english
https://qabel.de/en/imprint

**Comment by thechauffeur** [comment]
While using the mentioned correct imprint please leave out the last sentence (about links at the website).

**Comment by audax** [comment]
https://github.com/Qabel/qabel-desktop/pull/503
