### ISSUE TITLE
Change text to delete configuration file upon deinstallation

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-desktop#497]
The text is not very clear about the fact that this will delete all identities from the device which implies that -- without proper backups -- the user will not be able to gain access to her files again.

**Comment by julianseeger** [comment]
text missing

**Comment by audax** [comment]
https://redmine.qabel.de/issues/4847

**Comment by audax** [comment]
> Do you want to delete the configuration file?
> 
> If you delete the configuration file, your identities will be deleted as well and you will not be able to access your uploaded data anymore. Export your identities before you delete the configuration file, if you would still like to be able to access your data (e.g. from a different device or anytime in the future).
> 
> To export your identity, click on "Export identity" under "Identities" in your Qabel client.
> 
> Your identity contains your private key. Store it safely and don't pass it on to third parties.

---------------------------
> Wollen Sie die Konfigurationsdatei löschen?
> 
> Wenn Sie die Konfigurationsdatei löschen, werden auch Ihre Identitäten entfernt und Sie haben somit keinen Zugriff mehr auf Ihre hochgeladenen Daten. Exportieren Sie Ihre Identitäten, bevor Sie die Konfigurationsdatei löschen, wenn Sie weiterhin die Möglichkeit haben wollen, auf Ihre Daten zuzugreifen (z. B. von einem anderen Gerät oder irgendwann in der Zukunft).
> 
> Zum Export Ihrer Identität klicken Sie auf "Identität exportieren" unter "Identität" in Ihrem Qabel-Client.
> 
> Ihre Identität enthält Ihren privaten Schlüssel. Bewahren Sie die Datei also sicher auf und geben Sie sie nicht an Dritte weiter.

**Comment by audax** [comment]
@julianseeger the Text arrived!
