### ISSUE TITLE
Received chat messages from android app are not shown in desktop client

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-desktop#501]

**Comment by jan-schreib** [comment]
To reproduce: Install the desktop and android client from the website, create and share contacts and start to chat. Upgrade to the current beta version and try to chat again.
PC -> Android works.
Android -> PC does not work.

**Comment by julianseeger** [comment]
not reproducible

**Comment by julianseeger** [comment]
"website"=0.6.5-beta.2
"current beta version"=0.9.1-beta.3

**Comment by thechauffeur** [comment]
If both parties create a new identity (after the steps mentioned above) and exchanging contact information using Qabel Index chat messages are shown in both directions (i.e. it works then).

**Comment by thechauffeur** [comment]
However, accepting shares or open incoming shares (a .jpg) does not work on desktop. The other way around (On Android) it is working (shares sent from desktop).

**Comment by julianseeger** [comment]
It's because of the "old" dropState (timestamp) that's not a valid `X-Qabel-New-Since` header (out of range, probably because of the higher precision)
