### ISSUE TITLE
Received shares not usable without workaround

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-desktop#510]
Upon receiving a share it is shown in the chat screen but not in the file browser -> shares. It is possible to work around this by switching identities back and forth.

BTW: It is unclear for the user that received shares via chat screen are not clickable there but instead will only be usable in the file browser -> shares.

**Comment by julianseeger** [comment]
I didn't actually fix anything but with the code from https://github.com/Qabel/qabel-desktop/pull/513 I'm no longer able to reproduce this bug. Please retest when  #513 is merged

**Comment by thechauffeur** [comment]
I think it is only reproducible on Windows (it worked without #513 on Linux iirc).

**Comment by thechauffeur** [comment]
I will test it

**Comment by thechauffeur** [comment]
Fixed. Probably by #513.
