### ISSUE TITLE
Add Emoji support to chat

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-desktop#518]
Android ppl send nice emojis and I can't see them. That makes me sad ;-(

**Comment by enkore** [comment]
I can see them. Perhaps a font issue?

![2016-09-30-140715_2560x1440_scrot](https://cloud.githubusercontent.com/assets/1330164/18991212/4d1c1802-8717-11e6-9b4e-7cadd1fbfe26.png)

**Comment by audax** [comment]
It is just a font thing. Also, desktop keyboards usually don't have emoji buttons, so that's definitly something we should address.

**Comment by enkore** [comment]
Spike: Check if fallback font is possible.

**Comment by enkore** [comment]
Note: this is still required even with our move to double-dot emojis, because Android users can still send UTF-8 emoijs

**Comment by julianseeger** [comment]
FTR.: this does not happen when using the desktop client with ubuntu

**Comment by enkore** [comment]
The missing emojis or #520?

**Comment by julianseeger** [comment]
The emojis. It doesn't even Happen if launched from the IDE while using Windows. I think er just need to get the encoding of dropmessages right by always using explicit encoding when transforming Byte Arrays to Strings

**Comment by julianseeger** [comment]
emojis are fully working on the testdevice btw:
![pasted image at 2016_10_19 01_52 pm](https://cloud.githubusercontent.com/assets/3258762/19517875/14b1b476-9604-11e6-8914-eab9f157140c.png)

**Comment by julianseeger** [comment]
To answer the original question:
I couldn't get a fallback font working for single characters. In my tests, it either picked the first font or used the system fallback font (Segoe UI on Windows and Lucida Grande on MacOS with the addition that colored / image based fonts like Segoe UI Emoji can't be rendered). So we either have to rely on not using MacOS or on a emoji supporting default font like OpenSansEmoji (currently we are using *Source Sans Pro* which doesn't seem to contain emojis). Or we don't care and just replace them with images.

From left to right:
OpenSansEmoji with Source Sans Pro as fallback font
none defined (javafx windows default)
Source Sans Pro with OpenSansEmoji as fallback font
![image](https://cloud.githubusercontent.com/assets/3258762/19551645/8c3f2f66-96ac-11e6-82c5-14b913fe7d2e.png)
