### ISSUE TITLE
clickable links in chat

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#522]
extracted from https://github.com/Qabel/qabel-desktop/issues/519

Text is now copyable (as soon as #519 is implemented), so links can be copied into the browser, but clickable links would be far better in terms of usability. ~~Unfortunately, that feature is harder to implement than just selecting text (which was achieved by replacing the Label by a styled TextArea) so it was split out of the original ticket.~~

(needs to be discussed in terms of future enhancements ... images, code, citations, etc.)

**Comment by julianseeger** [comment]
http://fxexperience.com/controlsfx/features/
search for the HyperlinkLabel and done ...

**Comment by thechauffeur** [comment]
While both (see #519) are important it would be nice to have either one option ASAP. Whichever is less pain to implement.
