### ISSUE TITLE
tray icon event handling

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#525]
The tray icon behaves unintuitively (imho).

Doubleclicks should directly open the window.
The current context menu (on single left click) may better open on rightclick or be replaced by something useful (if doubleclick opens, we don't need a "show" entry) ... there is basically no limit on what to show like sync progress or the last arrived messages ...

**Comment by thechauffeur** [comment]
I would be good if it would open the window on double left click and showing the menu on right click instead of left click.

I would leave the content of the menu as it is now.

However, I 'm not sure if I would like to open the window on single left click and not just on double left click.

**Comment by enkore** [comment]
Single left click should open/raise window if window is opened already.
