### ISSUE TITLE
Sorting by Name/type/size in the file browser

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-desktop#530]
@audax commented on [Tue Oct 11 2016](https://github.com/Qabel/qabel-android/issues/743)

I want to sort the entries in the file browser by name, type or size.

**Comment by julianseeger** [comment]
you can already to that ...  don't know if it makes sense in a treeview and for filesizes it sorts by string representation but the feature is there:
![image](https://cloud.githubusercontent.com/assets/3258762/19289446/15888590-900b-11e6-88bb-745257a9716f.png)

**Comment by audax** [comment]
This was from a feedback, but maybe it was just about the android version.
