### ISSUE TITLE
Full Emoji Support in the chat

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-desktop#531]
@audax commented on [Tue Oct 11 2016](https://github.com/Qabel/qabel-android/issues/759)

Currently it is only possible to send utf-8 emojis and only by copy&pasting it.

I want a dedicated emoji selector.

- [X] emoji selector
- [ ] emoji selector inserts tags (:name:)
- [ ] converting tags -> unicode
- [ ] show unicode emojis as images

**Comment by julianseeger** [comment]
What about an emoji selector that sends / inserts utf-8 emojis?

**Comment by audax** [comment]
If we also ensure that we have font with nice utf-8 emojis, I think it would be good enough for now.

Maybe later we can add a new emoji-proider-microservice ;)

**Comment by audax** [comment]
https://github.com/pepibumur/emojize

**Comment by audax** [comment]
The emojis should be "slack-style" from the http://www.webpagefx.com/tools/emoji-cheat-sheet/

**Comment by julianseeger** [comment]
>The emojis should be "slack-style" from the http://www.webpagefx.com/tools/emoji-cheat-sheet/
@audax do you know which iconset that is? any .. links?

**Comment by julianseeger** [comment]
depends on https://github.com/Qabel/qabel-desktop/issues/522 code-wise

**Comment by julianseeger** [comment]
![image](https://cloud.githubusercontent.com/assets/3258762/19675770/907b9730-9a90-11e6-9bcb-73f4031bca40.png)
