### ISSUE TITLE
old syncs broken after update (maybe)

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#532]
I've got a sync setup from the current release and on the master I get a lot of events that are resolved with a `../` in the path and thus end up outside the sync dir:
![image](https://cloud.githubusercontent.com/assets/3258762/19285113/2cc96786-8ff9-11e6-99e4-31b6b24f6899.png)

Cannot reproduce this on new sync setups so that may be an issue introduces for existing syncs when integrating the cores dto.BoxPath. Needs further testing but I don't got time now.. maybe it's just my completely corrupted database but we need to make sure it is...

**Comment by jmt85** [comment]
please verify or close.

**Comment by julianseeger** [comment]
was only a ui bug ... some wasted cpu cycles, but nothing really bad happened
