### ISSUE TITLE
HighDPI-Scaling

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#538]

**Comment by julianseeger** [comment]
Increasing the font size seems to work best. But it doesn't fit out of the box so we would need do adjust a lot of layout. Needs further testing on an highdpi screen...

**Comment by audax** [comment]
It works just fine on Windows 10 on my Surface Pro 3. Scales nicely.

**Comment by julianseeger** [comment]
qabel @ highdpi := working
this theory is falsifiable, so until someone falsifies it, I see this issue as invalid
