### ISSUE TITLE
cross client sync of drop messages

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#549]
(from external feedback, not original but fixed grammar)

> When qabel is used on several devices and you open a chat on another device, you only see the received messages and not the sent messages of your own
> 
> Sent message multi device sync would be awesome

**Comment by thechauffeur** [comment]
Not sure if this should be in the core or if there are duplicates of this one.

**Comment by thechauffeur** [comment]
Issue moved to [Qabel/qabel-core #657](https://github.com/Qabel/qabel-core/issues/657) via [**ZenHub**](https://www.zenhub.com/)
