### ISSUE TITLE
Timestamps in chat messages are wrong (e.g. in the future)

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-desktop#554]
@julianseeger and I spoke about chat UI and observed this by accident. He can provide a screenshot.

**Comment by julianseeger** [comment]
![droptimefail](https://cloud.githubusercontent.com/assets/3258762/19732672/d134d144-9ba1-11e6-8f3b-539789e14a49.png)

**Comment by julianseeger** [comment]
On the receiver side (android), everything looks find and the timestamp for `or www.qabel.de` is about 17:07 ...

**Comment by julianseeger** [comment]
yea ... that was WIP code ^^
`new SimpleDateFormat("HH:ss")` ... seconds lol

**Comment by thechauffeur** [comment]
😁
