### ISSUE TITLE
Sharing not possible because share icon gone in remote file browser view

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-desktop#571]
<img width="900" alt="share_icon_gone" src="https://cloud.githubusercontent.com/assets/150507/19979011/2a31ecfc-a1f9-11e6-8957-5450cf1b4fac.png">

This is confirmed by @kikithegecko.

**Comment by kikithegecko** [comment]
I found out that the sharing icon (as well as the delete icon) will appear only on the last file in the current file listing. If you enter a search query that results in the desired file being the last one in the list, the share icon appears and sharing is possible (I just tested this with @thechauffeur).
