### ISSUE TITLE
Desktop version for Linux-based operating systems

### ISSUE THREAD

**Issue by baimafeima** [Qabel/qabel-desktop#581]
Are there currently any plans to support Linux-based operating systems?

**Comment by thechauffeur** [comment]
There are currently no plans to offer support for linux-based OS. However, the application was developed mostly on linux and works just fine. You can start it with the gradle targed "client:run" for example.
However, the registration for Qabel accounts is currently closed. We will terminate the services Qabel Free and Qabel Plus effective December 1st 2017, see [1]. You are however free to host your own Qabel cloud, as all required components are free for private use and can be found here on GitHub.

[1] https://qabel.de/en/download
