### ISSUE TITLE
Installation and Updating - installer windows

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#67]
It must exits a installation file for Windows Desktop that install the qabel box.

**Comment by julianseeger** [comment]
waiting for #114  (will speed up this issue)

**Comment by julianseeger** [comment]
ftr: this issue is on hold till we have more feedback or even a decision

**Comment by julianseeger** [comment]
* Pleae look closer at:
** JWrapper (@jmt85 doen't recommend this one)
** Inno Setup
** Install4J (I recommend this one)
