### ISSUE TITLE
Installation and Updating - update polling

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-desktop#70]
The Qabel Box must check if a new version from the qabel box is available. Is a update available the user made available the link to the update site.

**Comment by julianseeger** [comment]
maybe hockeyapp can handle this

**Comment by julianseeger** [comment]
waiting for https://github.com/Qabel/qabel-accounting/issues/55

**Comment by jmt85** [comment]
infos available:  https://files.qabel.de/etc/versions.json
